name: compile cons_tres_cloud
on: [push]
jobs:
    Compile:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ["25.05", "25.11", "26.05"]
        steps:
            - run: sudo apt install libmunge-dev
            - uses: actions/checkout@v6
            - id: release-url
              run: |
                URL=$(curl https://api.github.com/repos/schedmd/slurm/releases | jq -r '.[] | select(.name | contains("${{ matrix.version }}")) | .assets[0].browser_download_url ' | head -n1)
                echo "value=${URL}" >> $GITHUB_OUTPUT
            - run: curl -L -O ${{ steps.release-url.outputs.value }}
            - run: tar xf slurm-*.tar.bz2
            - run: mv slurm*/ slurm/
            - run: |
                cd slurm
                cat ../patches/${{ matrix.version }}/*.patch | patch -p1
                ./configure
                make -j4
            - name: Archive code coverage results
              uses: actions/upload-artifact@v6
              with:
                name: slurm-${{ matrix.version }}
                path: slurm/src/plugins/select/cons_tres/.libs/select_cons_tres.so