name: compile cons_tres_cloud
on: [push]
jobs:
    Compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                sparse-checkout: |
                    src
            - run: git clone https://github.com/SchedMD/slurm.git
            - run: sudo apt install libmunge-dev
            - run: |
                cd slurm
                git checkout slurm-24-11-7-1
                cp ../src/job_test.c src/plugins/select/cons_tres/
                ./configure
                cd slurm/src/plugins/select/cons_tres/
                make
                cp .libs/select_cons_tres.so ~/