name: compile cons_tres_cloud
on: [push]
jobs:
    Compile:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ["25.11.3", "25.05.6"]
        steps:
            - run: sudo apt install libmunge-dev
            - uses: actions/checkout@v6
              with:
                sparse-checkout: |
                    src
            - run: curl -L -O https://download.schedmd.com/slurm/slurm-${{ matrix.version }}.tar.bz2
            - run: tar xf slurm-*.tar.bz2
            - run: mv slurm*/ slurm/
            - run: |
                cd slurm
                cp ../src/job_test.c src/plugins/select/cons_tres/
                ./configure
                cd src/plugins/select/cons_tres/
                make
                cp .libs/select_cons_tres.so ~/
            - name: Archive code coverage results
              uses: actions/upload-artifact@v4
              with:
                name: slurm-${{ matrix.version }}
                path: select_cons_tres.so